site_name: Extractional Documentation
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  favicon: img/icon_transparent.png
  logo: img/icon_transparent.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: cyan
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: custom
      accent: cyan

plugins:
  - glightbox
  - search
  - macros:
      include_dir: docs/assets
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: French
          build: true
        - locale: de
          name: German
          build: true
#   - social

extra:
  social:
    - icon: fontawesome/regular/clone
      link: https://extractional.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Extractional

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md

  - Introduction: System Overview and User Management.md

  - System Overview:
    - System Overview: System Overview/index.md
    - Dashboard: System Overview/Dashboard.md
    - Template: System Overview/Template.md
    - Validations: System Overview/Validations.md
    - Tools: System Overview/Tools.md
    - Users: System Overview/Users.md
    - Settings: System Overview/Settings.md
  
  - Peppol:
    - Peppol: Peppol/Introduction.md
    - Prerequisites: Peppol/Prerequisites.md
    - Documentation with Peppol: Peppol/Documentation_with_Peppol.md
    - Tools with Peppol: Peppol/Tools_with_Peppol.md

  - Multi tenant system:
    - Multi tenant system: Multi tenant system/index.md
    - Setting up the system: Multi tenant system/Setting up the system.md

  - FAQ: FAQ.md
extra_css:
  - stylesheets/extra.css
# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# copyright: |
#   &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>