site_name: Extractional Documentation

theme:
  name: material
  favicon: img/icon_transparent.png
  logo: img/icon_transparent.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: cyan
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: custom
      accent: cyan

plugins:
  - glightbox
  - search
  - macros:
      include_dir: docs/assets
  - exporter:
      logging:
            level: debug
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 16
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
            # back: resources/templates/covers/front.html.j2
          browser:
            debug: false
          aggregator:
            enabled: true
            output: documentation.pdf
            covers: front
      buttons:
        - title: View as PDF
          icon: material-file-move-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  # - with-pdf:
  #     palette: custom
  #     output_path: pdf/manual.pdf
  #     cover_title: My Software Manual
  #     cover_subtitle: Version 1.0
  #     author: Andre Martins
  #     toc_title: Table of Contents
  #     # Define which docs to include and in what order
  #     exclude:
  #       - index.md
#   - social

extra:
  social:
    - icon: fontawesome/regular/clone
      link: https://extractional.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Extractional

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md

  - Introduction: System Overview and User Management.md

  - System Overview:
    - Home: System Overview/index.md
    - Dashboard: System Overview/Dashboard.md
    - Template: System Overview/Template.md

  - Multi tenant system:
    - Home: Multi tenant system/index.md
    - Setting up the system: Multi tenant system/Setting up the system.md
extra_css:
  - stylesheets/extra.css
# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# copyright: |
#   &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>